version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_PORT=4587
      - DB_USER=jarvis
      - DB_PASSWORD=jarvis
      - DB_NAME=euphron
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
    command: [ "npm", "run", "prod" ]

  app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest-api-dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_PORT=4587
      - DB_USER=jarvis
      - DB_PASSWORD=jarvis
      - DB_NAME=euphron
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules

  db:
    image: mariadb:11.5
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: euphron
      MARIADB_USER: jarvis
      MARIADB_PASSWORD: jarvis
    ports:
      - "4587:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
