FROM node:23-alpine

WORKDIR /usr/src/app

# Ajout de basg=h et colorisation
RUN apk add --no-cache bash
ENV TERM=xterm-256color
RUN echo "PS1='\e[92m\u\e[0m@\e[94m\h\e[0m:\e[35m\w\e[0m# '" >> /root/.bashrc

COPY package*.json ./
COPY . .

# Install the dependencies
RUN npm install -g @nestjs/cli
RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]