version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=website
      - DB_PASSWORD=your_password
      - DB_NAME=euphron
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
    command: [ "npm", "run", "prod" ]

  db:
    image: mariadb:11.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: euphron
      MYSQL_USER: jarvis
      MYSQL_PASSWORD: jarvis
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
